- hosts: k3s_cluster_servers
  gather_facts: false
  tasks:
    - name: Setup JunoFX Orion Cluster Supporting Infrastructure Servers
      include_role:
        name: orion
      vars:
        fully_restore_cluster: true
        k3s_installation_target: server
        deployment_scope: cluster

- hosts: k3s_cluster_cpu_agents
  gather_facts: true
  tasks:
    - name: Setup JunoFX Orion Cluster Supporting Infrastructure for CPU Nodes
      include_role:
        name: orion
      vars:
        fully_restore_cluster: true
        k3s_installation_target: agent
        deployment_scope: cluster
        node_type: cpu

- hosts: k3s_cluster_gpu_agents
  gather_facts: true
  tasks:
    - name: Setup JunoFX Orion Cluster Supporting Infrastructure for GPU Nodes
      include_role:
        name: orion
      vars:
        fully_restore_cluster: true
        k3s_installation_target: agent
        deployment_scope: cluster
        node_type: gpu

- hosts: localhost
  vars:
    ansible_roles_path: roles
  tasks:
    - name: "Bootstrap JunoFX Orion Cluster Supporting Infrastructure Supporting App Components..."
      include_role:
        name: orion
      vars:
        deployment_scope: apps
        install_argocd: true
        install_gpu_operator: true
        install_nginx_operator: true
