- name: Install required packages for Debian
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install required packages for RHEL
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Add Docker GPG key for Debian
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Add Docker GPG key for RHEL
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Add Docker repository for Debian
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Add Docker repository for RHEL
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  become: true

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
