- name: Create Docker registry secret
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k3s_kubeconfig_path }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ docker_registry_secret_name }}"
        namespace: "{{ namespace }}"
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ {'auths': {docker_server: {'username': docker_registry_username, 'password': docker_registry_password, 'auth': (docker_registry_username + ':' + docker_registry_password) | b64encode}}} | to_json | b64encode }}"
  register: secret_result

- name: Show result
  debug:
    msg: "Secret {{ docker_registry_secret_name }} has been {{ secret_result.method }} in namespace {{ namespace }}"